# Generated by Django 3.2.8 on 2021-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio_meta', models.DateField()),
                ('data_fim_meta', models.DateField()),
                ('concluida', models.BooleanField()),
            ],
        ),
    ]
