# Generated by Django 3.2.8 on 2021-11-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAjuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.categoriaajuda')),
            ],
        ),
    ]
