# Generated by Django 3.2.8 on 2021-11-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_categoriaajuda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
