# Generated by Django 3.2.8 on 2021-11-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaAjuda',
        ),
    ]
