# Generated by Django 3.2.8 on 2021-11-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_inicio_comp', models.DateField(blank=True, null=True)),
                ('tamanho_comp', models.IntegerField(blank=True, null=True)),
                ('total_humus_produzido', models.FloatField(blank=True, null=True)),
                ('concluido', models.BooleanField(blank=True, null=True)),
                ('data_conclusao_comp', models.DateField(blank=True, null=True)),
                ('qualidade', models.BooleanField(blank=True, null=True)),
                ('humus_produzido', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Composteira',
            },
        ),
    ]
