# Generated by Django 3.2.8 on 2021-11-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
        ('meta', '0001_initial'),
        ('acompanhamentoComposteira', '0001_initial'),
        ('composteira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composteira',
            name='acompanhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acompanhamentoComposteira.acompanhamentocomposteira'),
        ),
        migrations.AddField(
            model_name='composteira',
            name='insumo',
            field=models.ManyToManyField(to='insumo.Insumo', verbose_name='Lista de Insumos'),
        ),
        migrations.AddField(
            model_name='composteira',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.meta'),
        ),
    ]
