# Generated by Django 3.2.8 on 2021-12-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentoComposteira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentocomposteira',
            name='pontuacao_acomp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
