# Generated by Django 3.2.8 on 2021-12-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentoComposteira', '0003_alter_acompanhamentocomposteira_pontuacao_acomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentocomposteira',
            name='erro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acompanhamentocomposteira',
            name='msg_erro',
            field=models.CharField(default='Erros encontrados! para resolvê-los faça as seguintes alterações:\n', max_length=500),
        ),
    ]
