# Generated by Django 3.2.8 on 2021-12-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentoComposteira', '0002_alter_acompanhamentocomposteira_pontuacao_acomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentocomposteira',
            name='pontuacao_acomp',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
