# Generated by Django 3.2.8 on 2021-11-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('insumo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_insumo', models.CharField(max_length=20)),
                ('qtd_insumo', models.IntegerField(blank=True, null=True)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('retirado', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
