# Generated by Django 3.2.8 on 2021-11-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classificacao', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='classificacao_insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classificacao.classificacao'),
        ),
    ]
