# Generated by Django 3.2.8 on 2021-11-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_insumo_classificacao_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='insumo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
