# Generated by Django 3.2.8 on 2021-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentoComposteira', '0001_initial'),
        ('meta', '0001_initial'),
        ('composteira', '0002_composteira_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composteira',
            name='acompanhamento',
        ),
        migrations.AddField(
            model_name='composteira',
            name='acompanhamento',
            field=models.ManyToManyField(to='acompanhamentoComposteira.AcompanhamentoComposteira', verbose_name='Lista de Acompanhamento'),
        ),
        migrations.RemoveField(
            model_name='composteira',
            name='meta',
        ),
        migrations.AddField(
            model_name='composteira',
            name='meta',
            field=models.ManyToManyField(to='meta.Meta', verbose_name='Lista de Metas'),
        ),
    ]
