# Generated by Django 3.2.8 on 2021-12-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desempenhoMeta', '0001_initial'),
        ('composteira', '0003_auto_20211201_2331'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta',
            new_name='MetaCompost',
        ),
    ]
