"""
Django settings for cadastro project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "g(ugnz#7lb$jbex0q4vtc=uh@do#(zru_qzk+z!@ll@yeg=k#y"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#HTTPS
#SECURE_SSL_REDIRECT = False
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#COOKIES
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    # django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # 3rd party
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "crispy_forms",
    # local
    "users.apps.UsersConfig",
    "pages.apps.PagesConfig",
    "composteira.apps.ComposteiraConfig",
    "insumo.apps.InsumoConfig",
    "acompanhamentoComposteira.apps.AcompanhamentoComposteiraConfig",
    "ajuda.apps.AjudaConfig",
    "classificacao.apps.ClassificacaoConfig",
    "desempenhoMeta.apps.DesempenhoMetaConfig",
    "meta.apps.MetaConfig",
    "notificacaoMeta.apps.NotificacaoMetaConfig",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cadastro.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cadastro.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
   # "default": {
   #     "ENGINE": "django.db.backends.postgresql",
   #     "NAME": 'dbg3asv1h7ljq3',
   #     "USER": 'omtrjwmznudpwt',
   #     "PASSWORD": '782010bc87b76502772520df323553d78ab5862f786f4935a552e1142c733a5f',
   #     "HOST": 'ec2-52-200-68-5.compute-1.amazonaws.com',
   #     "PORT": 5432,
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": 'dcrmac5dn96k4v',
        "USER": 'izzxlwwzhcfjai',
        "PASSWORD": '696f286be90a66c297126a2b9229964329e2d24018e8f45e2bfa5433a5656c8a',
        "HOST": 'ec2-3-225-2-236.compute-1.amazonaws.com',
        "PORT": 5432,
    }
}
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LANGUAGE_PATHS = [
    os.path.join(BASE_DIR, ''),  # base folder where manage.py resides
    os.path.join(BASE_DIR, '/locale')  # app folder
]

LANGUAGE_CODE = 'en'
USE_I18N = True
LANGUAGES = (
    ('pt-br', ("Portugues")),
    ('en', ("Ingles"))
)

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
import os
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "cadastro/static"),
    # '/var/www/static/',
)



# Django-allauth

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
LOGIN_REDIRECT_URL = "/"
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True


# crispy-forms

CRISPY_TEMPLATE_PACK = "bootstrap4"

# Configure Django App for Heroku.
import django_heroku
django_heroku.settings(locals())