# Generated by Django 3.2.9 on 2021-11-29 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classificacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_insumo', models.CharField(max_length=20)),
                ('qtd_insumo', models.IntegerField(blank=True, null=True)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('retirado', models.BooleanField(blank=True, null=True)),
                ('classificacao_insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classificacao.classificacao')),
            ],
        ),
    ]
