# Generated by Django 3.2.8 on 2021-12-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='data_inclusao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
