# Generated by Django 3.2.8 on 2021-12-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_alter_insumo_data_inclusao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insumo',
            table='insumo',
        ),
    ]
