# Generated by Django 3.2.9 on 2021-11-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesempenhoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_concluido', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'desempenhoMeta',
            },
        ),
    ]
