# Generated by Django 3.2.8 on 2021-11-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_classificação', models.CharField(blank=True, max_length=10, null=True)),
                ('pontuacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Classificacao',
            },
        ),
    ]
